### ISSUE TITLE
Feature request: more then one exchange rate

### ISSUE THREAD

**Issue by andreas-helm** [daninfpj/currency-exchange#1]
Hey,

is there a possibility to show more then only one exchange rate?

For example: i type "cur 100 eur" and the result shows me my 5 favorite rates (USD, GBP, CHF, JPY AUD) instead of just one? Would be a great feature

**Comment by daninfpj** [comment]
That makes sense, thanks for the suggestion. I'll add this on the next release.

**Comment by daninfpj** [comment]
Added in v0.1.2
