### ISSUE TITLE
似乎不能转化小数？

### ISSUE THREAD

**Issue by elviscai** [daninfpj/currency-exchange#3]
![xnip2019-01-10_15-27-41](https://user-images.githubusercontent.com/1329768/50952760-645a7d00-14ec-11e9-987c-1d8225f3ac6f.png)

输入 4.99，转的却是 4 😂

**Comment by daninfpj** [comment]
I think 33.88 is the correct value (equivalent for 4.99) but it’s being displayed incorrectly.

Thanks for the report, will fix.
