### ISSUE TITLE
Error in workflow 'Currency Exchange'

### ISSUE THREAD

**Issue by M165437** [daninfpj/currency-exchange#5]
Hi Daniel,

I've updated to Alfred 3.8 (released 2nd Feb 2019) and having trouble with this workflow since.

<img width="580" alt="bildschirmfoto 2019-02-13 um 18 33 45" src="https://user-images.githubusercontent.com/711773/52745728-8ef19700-2fbe-11e9-96d3-ef729eab36a7.png">

Any idea what could be causing this error?

Great workflow by the way!

**Comment by lilaboc** [comment]
can confirm the same issue with Alfred 3.8

**Comment by LeeDashan** [comment]
can confirm the same issue with Alfred 3.8

**Comment by M165437** [comment]
I had a look at Alfred’s debugging console. It outputs the following error:

```
[2019-02-20 09:08:38][ERROR: input.scriptfilter] Code 1: 09:08:35 workflow.py:2247 DEBUG    ---------- Currency Exchange (0.1.0) ----------
09:08:35 workflow.py:1657 DEBUG    reading settings from /Users/Michael/Library/Application Support/Alfred 3/Workflow Data/co.theengineer.currencyExchange/settings.json
09:08:38 workflow.py:2266 ERROR    'NoneType' object has no attribute 'read'
Traceback (most recent call last):
  File "/Users/Michael/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.85DDA728-8CD7-4393-9AB1-B9DBC83D8149/workflow/workflow.py", line 2259, in run
    func(self)
  File "convert.py", line 44, in main
    rate = get_rate_alt(fr, to)
  File "convert.py", line 82, in get_rate_alt
    data = web.get('http://free.currencyconverterapi.com/api/v3/convert?q=%s_%s&compact=ultra' % (fr, to)).json()
  File "/Users/Michael/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.85DDA728-8CD7-4393-9AB1-B9DBC83D8149/workflow/web.py", line 271, in json
    return json.loads(self.content, self.encoding or 'utf-8')
  File "/Users/Michael/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.85DDA728-8CD7-4393-9AB1-B9DBC83D8149/workflow/web.py", line 302, in content
    self._content = self.raw.read()
AttributeError: 'NoneType' object has no attribute 'read'
09:08:38 workflow.py:2289 DEBUG    ---------- finished in 3.049s ----------
```

So, looking at `convert.py` line 44 and 82, this is where the current conversion rate is being requested  via API (with a second API as a fallback). Both APIs return error messages:

`http://free.currencyconverterapi.com/api/v3/convert?q=usd_eur&compact=ultra` returns
```
{"status":400,"error":"API Key is required."}
```

and `http://apilayer.net/api/live?access_key=c938bcf13e0aff152614745f41414ed4&currencies=usd,eur` returns

```
{"success":false,"error":{"code":104,"info":"Your monthly usage limit has been reached. Please upgrade your Subscription Plan."}}
```

**A quick fix**: I requested a free API key from currencyconverterapi.com at https://free.currencyconverterapi.com/free-api-key and added it to the API call in `convert.py`at line 82

```
data = web.get('http://free.currencyconverterapi.com/api/v3/convert?q=%s_%s&compact=ultra&apiKey=my-api-key' % (fr, to)).json()
```

@daninfpj Maybe this key could be requested by each user and added via Alfred interface?

**Comment by daninfpj** [comment]
Thanks for taking the time to look into this.

I haven’t had a lot of time lately, but will fix this by the end of this week.

There is a problem with those API keys, I just left those as I was the only one using it but knew it was going to be an issue once a few people were using it. However, I think it’s too much of a hassle having to register to get your own API keys. So I’ll try to think of an alternative.

**Comment by LeeDashan** [comment]
Go to this website (https://free.currencyconverterapi.com/free-api-key) and register a free api_key.

Then open the convert.py, go to line 105, add append the free api_key to the request url.

It workes

**Comment by daninfpj** [comment]
Fixed in [v1.0.3](https://github.com/daninfpj/currency-exchange/releases/tag/1.0.3)

**Comment by M165437** [comment]
@daninfpj May I ask what solution you came up with?

**Comment by daninfpj** [comment]
@M165437 I added a free key as you suggested, it allows for up to 100 requests per hour, so it should be good for now.

But the longer term solution is going to be adding your own API key via Alfred, similar to how you set the currencies now.

**Comment by M165437** [comment]
I don't even think that it's too much of a hassle for the user. That way we're not all sharing one quota. :) Thanks for the update.

**Comment by viktorbijlenga** [comment]
Thanks for the quick bugfix!

**Comment by shcode** [comment]
Why not add a command to enter the api key?

**Comment by daninfpj** [comment]
@shcode Yup! That’s coming in the next release.
