### ISSUE TITLE
Please enter a valid format

### ISSUE THREAD

**Issue by draxvint** [daninfpj/currency-exchange#7]
I got this error often. I don't know why, but sometimes work, sometimes not.

![image](https://user-images.githubusercontent.com/1795922/53207156-4035a400-3633-11e9-89a0-7eef96892384.png)

**Comment by daninfpj** [comment]
Duplicate: #5 
Fixed in [v1.0.3](https://github.com/daninfpj/currency-exchange/releases/tag/1.0.3)

**Comment by draxvint** [comment]
Thank you!

**Comment by draxvint** [comment]
~~I get this error again  :(~~

EDIT: The API is under maintance:
{"status":400,"error":"Server is in maintenance mode. Estimated downtime: 12 hrs."}
